language: rust
rust:
  - stable
  - beta
cache: cargo
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - cargo test
  - ./run-mal-tests